"""
This mock dataset generation was generated by Claude
during the prototyping with chat discussion
and reviewed/edited by the project team
"""
import sqlite3
import os
from datetime import datetime, timedelta

# -------------------------------------------------------
# CONNECTION
# Path resolves to database/loop_scavenger_hunt.db
# relative to the repo root.
# Run from repo root: python3 database/seeds/seed_mock_data.py
# -------------------------------------------------------
DB_PATH = os.path.join(os.path.dirname(__file__), "..", "chica_go.db")
conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

# Enable FK enforcement for this session — required every connection in SQLite
cursor.execute("PRAGMA foreign_keys = ON")

# -------------------------------------------------------
# SEED: point_of_interests — STATIONS
#
# SELF-REFERENCING INSERT PATTERN (required for station rows):
#   Stations identify themselves by having station_id == their own id.
#   Since the id is auto-assigned, we cannot know it before insert.
#   Step 1: INSERT with station_id = NULL (placeholder)
#   Step 2: UPDATE SET station_id = id once the id is known
#
# DO NOT attempt to set station_id on the initial INSERT for stations —
# the id doesn't exist yet and the FK would reject it.
# -------------------------------------------------------
stations_raw = [
    # (poi_name, longitude, latitude, points)
    ("Harold Washington Library Station", -87.627800, 41.876200, 10),
    ("Millennium Station",                -87.624500, 41.884400, 10),
    ("Chicago/State Station",             -87.627900, 41.896900, 10),
    ("Clark/Lake Station",                -87.631700, 41.885700, 10),
    ("Adams/Wabash Station",              -87.626300, 41.879700, 10),
]

station_map = {}  # maps station_name → assigned id, used when seeding POIs below

for (poi_name, longitude, latitude, points) in stations_raw:
    # Step 1: insert with station_id = NULL
    cursor.execute(
        "INSERT INTO point_of_interests (poi_name, longitude, latitude, station_id, points) VALUES (?, ?, ?, NULL, ?)",
        (poi_name, longitude, latitude, points)
    )
    new_id = cursor.lastrowid

    # Step 2: set station_id = its own id (self-reference marks this row as a station)
    cursor.execute(
        "UPDATE point_of_interests SET station_id = ? WHERE id = ?",
        (new_id, new_id)
    )
    station_map[poi_name] = new_id

print(f"Inserted {len(stations_raw)} stations")

# -------------------------------------------------------
# SEED: point_of_interests — NEARBY POIs
#
# These rows have station_id pointing to a different row (a station).
# station_id != id → this row is a POI linked to a parent station.
# station_id = NULL → standalone POI, not anchored to any station.
# -------------------------------------------------------
pois_raw = [
    # (poi_name, longitude, latitude, station_id_lookup_name, points)
    # station_id_lookup_name matches a key in station_map; None = standalone
    ("Harold Washington Library",  -87.627200, 41.876100, "Harold Washington Library Station", 5),
    ("Grant Park",                 -87.619000, 41.876400, "Millennium Station",                  5),
    ("Art Institute of Chicago",   -87.623600, 41.879400, "Adams/Wabash Station",               5),
    ("Millennium Park",            -87.622700, 41.882600, "Millennium Station",                   5),
    ("Chicago Riverwalk",          -87.630700, 41.888500, "Clark/Lake Station",                   5),
    ("Cloud Gate (The Bean)",      -87.623300, 41.882700, None,                                   5),  # standalone
    ("Chicago Cultural Center",    -87.624600, 41.883100, None,                                   5),  # standalone
]

for (poi_name, longitude, latitude, station_lookup, points) in pois_raw:
    station_id = station_map.get(station_lookup) if station_lookup else None
    cursor.execute(
        "INSERT INTO point_of_interests (poi_name, longitude, latitude, station_id, points) VALUES (?, ?, ?, ?, ?)",
        (poi_name, longitude, latitude, station_id, points)
    )

print(f"Inserted {len(pois_raw)} POIs")

# -------------------------------------------------------
# SEED: profiles
# Mock players with varying scores
# -------------------------------------------------------
profiles = [
    # (username, email, password_hash, hi_score, weekly_score)
    ("LoopRunner99", "runner99@example.com", "hashed_pw_1", 340, 120),
    ("BeanSeeker",   "bean@example.com",     "hashed_pw_2", 210,  90),
    ("CTAChaser",    "cta@example.com",      "hashed_pw_3", 580, 200),
    ("WabashWalker", "wabash@example.com",   "hashed_pw_4",  75,  75),
    ("LoopNewbie",   "newbie@example.com",   "hashed_pw_5",   0,   0),
]

cursor.executemany(
    "INSERT INTO profiles (username, email, password_hash, hi_score, weekly_score) VALUES (?, ?, ?, ?, ?)",
    profiles
)
print(f"Inserted {len(profiles)} profiles")

# -------------------------------------------------------
# SEED: stamp_books + stamp_book_entries
# One stamp book per profile.
# One entry per POI (all rows in point_of_interests) per book — visited = 0 by default.
# This is the Pokédex pattern: every slot exists from day one.
# -------------------------------------------------------
cursor.execute("SELECT id FROM profiles ORDER BY id")
profile_ids = [row[0] for row in cursor.fetchall()]

cursor.execute("SELECT id FROM point_of_interests ORDER BY id")
poi_ids = [row[0] for row in cursor.fetchall()]

for profile_id in profile_ids:
    cursor.execute(
        "INSERT INTO stamp_books (profile_id) VALUES (?)",
        (profile_id,)
    )
    book_id = cursor.lastrowid  # SQLite equivalent of RETURNING id

    for poi_id in poi_ids:
        cursor.execute(
            "INSERT INTO stamp_book_entries (stamp_book_id, location_id, visited, visited_at) VALUES (?, ?, 0, NULL)",
            (book_id, poi_id)
        )

print(f"Created {len(profile_ids)} stamp books with {len(poi_ids)} entries each")

# -------------------------------------------------------
# SEED: mark 3 stamps as visited for LoopRunner99
# Simulates a mid-game player for demo purposes
# -------------------------------------------------------
cursor.execute("SELECT id FROM profiles WHERE username = 'LoopRunner99'")
runner_id = cursor.fetchone()[0]

cursor.execute("SELECT id FROM stamp_books WHERE profile_id = ?", (runner_id,))
runner_book_id = cursor.fetchone()[0]

for i, poi_id in enumerate(poi_ids[:3]):
    visit_time = (datetime.utcnow() - timedelta(hours=3 - i)).isoformat()
    cursor.execute(
        "UPDATE stamp_book_entries SET visited = 1, visited_at = ? WHERE stamp_book_id = ? AND location_id = ?",
        (visit_time, runner_book_id, poi_id)
    )

print("Marked 3 stamps as visited for LoopRunner99")

# -------------------------------------------------------
# VERIFICATION QUERIES — printed to console after seeding
# -------------------------------------------------------
print("\n--- Verification ---")

# Show all POIs with their type (station / linked POI / standalone)
cursor.execute("""
    SELECT
        id,
        poi_name,
        station_id,
        CASE
            WHEN station_id IS NULL         THEN 'standalone'
            WHEN station_id = id            THEN 'station'
            ELSE                                 'poi → station ' || station_id
        END AS poi_type,
        points
    FROM point_of_interests
    ORDER BY id
""")
print("\npoint_of_interests:")
print(f"  {'id':<4} {'poi_name':<40} {'station_id':<12} {'poi_type':<25} {'pts'}")
for row in cursor.fetchall():
    print(f"  {row[0]:<4} {row[1]:<40} {str(row[2]):<12} {row[3]:<25} {row[4]}")

# Show LoopRunner99's stamp book
cursor.execute("""
    SELECT
        p.username,
        poi.poi_name,
        sbe.visited,
        sbe.visited_at
    FROM profiles p
        JOIN stamp_books sb         ON sb.profile_id = p.id
        JOIN stamp_book_entries sbe ON sbe.stamp_book_id = sb.id
        JOIN point_of_interests poi ON poi.id = sbe.location_id
    WHERE p.username = 'LoopRunner99'
    ORDER BY sbe.visited DESC, sbe.visited_at ASC
""")
print("\nLoopRunner99 stamp book:")
print(f"  {'poi_name':<40} {'visited':<8} {'visited_at'}")
for row in cursor.fetchall():
    print(f"  {row[1]:<40} {str(row[2]):<8} {row[3] or 'None'}")

# -------------------------------------------------------
# COMMIT AND CLOSE
# -------------------------------------------------------
conn.commit()
cursor.close()
conn.close()
print("\nMock data seeding complete — chica_go.db is ready.")