"""
This mock dataset generation was generated by Claude
during the prototyping with chat discussion
and reviewed/edited by the project team
"""
import sqlite3
import os
from datetime import datetime, timedelta
import Parser

# -------------------------------------------------------
# CONNECTION
# Path resolves to database/loop_scavenger_hunt.db
# relative to the repo root.
# Run from repo root: python3 database/seeds/seed_mock_data.py
# -------------------------------------------------------
DB_PATH = os.path.join(os.path.dirname(__file__), "..", "chica_go.db")
conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

# Enable FK enforcement for this session — required every connection in SQLite
cursor.execute("PRAGMA foreign_keys = ON")

# -------------------------------------------------------
# SEED: point_of_interests — STATIONS
#
# SELF-REFERENCING INSERT PATTERN (required for station rows):
#   Stations identify themselves by having station_id == their own id.
#   Since the id is auto-assigned, we cannot know it before insert.
#   Step 1: INSERT with station_id = NULL (placeholder)
#   Step 2: UPDATE SET station_id = id once the id is known
#
# DO NOT attempt to set station_id on the initial INSERT for stations —
# the id doesn't exist yet and the FK would reject it.
# -------------------------------------------------------

stations_raw, pois_raw = Parser.build_poi_list("poi.geojson", "stations.geojson")


station_map = {}  # maps station_name → assigned id, used when seeding POIs below

for _station in stations_raw:
    poi_name = _station['name']
    longitude = _station['longitude']
    latitude = _station['latitude']
    points = _station['points']

    # Step 1: insert with station_id = NULL
    cursor.execute(
        "INSERT INTO point_of_interests (poi_name, longitude, latitude, station_id, points) VALUES (?, ?, ?, NULL, ?)",
        (poi_name, longitude, latitude, points)
    )
    new_id = cursor.lastrowid

    # Step 2: set station_id = its own id (self-reference marks this row as a station)
    cursor.execute(
        "UPDATE point_of_interests SET station_id = ? WHERE id = ?",
        (new_id, new_id)
    )
    station_map[poi_name] = new_id

print(f"Inserted {len(stations_raw)} stations")

# -------------------------------------------------------
# SEED: point_of_interests — NEARBY POIs
#
# These rows have station_id pointing to a different row (a station).
# station_id != id → this row is a POI linked to a parent station.
# station_id = NULL → standalone POI, not anchored to any station.
# -------------------------------------------------------

for _poi in pois_raw:
    poi_name = _station['name']
    longitude = _station['longitude']
    latitude = _station['latitude']
    station_lookup = _station['nearest_station']
    points = _station['points']
    station_id = station_map.get(station_lookup) if station_lookup else None
    cursor.execute(
        "INSERT INTO point_of_interests (poi_name, longitude, latitude, station_id, points) VALUES (?, ?, ?, ?, ?)",
        (poi_name, longitude, latitude, station_id, points)
    )

print(f"Inserted {len(pois_raw)} POIs")

conn.commit()
cursor.close()
conn.close()
print("\nMock data seeding complete — chica_go.db is ready.")