-- =============================================================================
-- THE LOOP SCAVENGER HUNT — CORRECTED DATABASE SCHEMA
-- This document was generated by Claude bsed on a prototype implementation
-- =============================================================================
-- TABLE INTERACTION OVERVIEW:
--
--   users (1) ──────────────────────── (1) stamp_books
--                                            │
--                               (1) ─────────┴──────── (many) stamp_book_entries
--                                                               │
--                               (many) ────────────────────────┘── (1) point_of_interests
--                                                                         │
--                               (many) ────────────────────────────────── (1) stations
--
--   A USER owns exactly one STAMP_BOOK.
--   A STAMP_BOOK contains many STAMP_BOOK_ENTRIES — one slot per POI, visited or not.
--   Each STAMP_BOOK_ENTRY references one POINT_OF_INTEREST (the location being stamped).
--   Each POINT_OF_INTEREST optionally belongs to a STATION (its nearest CTA stop).
--   STATIONS are standalone — they exist independently of any POI.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- TABLE: users
-- -----------------------------------------------------------------------------
-- Root entity. Every other table traces back to a user either directly (stamp_books)
-- or indirectly (stamp_book_entries → stamp_books → users).
-- ON DELETE CASCADE on child tables means deleting a user cleans up everything
-- downstream automatically — no orphaned stamp books or entries.
-- -----------------------------------------------------------------------------
CREATE TABLE profiles (
    id            BIGSERIAL    PRIMARY KEY,             -- internal DB key, not exposed as a "user ID" in UI
    username      VARCHAR(50)  NOT NULL UNIQUE,         -- display name, must be unique across all players
    email         VARCHAR(255) NOT NULL UNIQUE,         -- login credential, unique per account
    password_hash VARCHAR(255) NOT NULL,                -- BCrypt hash — never store plaintext
    hi_score      INT          NOT NULL DEFAULT 0,      -- all-time best score, survives weekly resets
    weekly_score  INT          NOT NULL DEFAULT 0,      -- resets every Monday via scheduled job
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW()   -- account creation timestamp
);


-- -----------------------------------------------------------------------------
-- TABLE: stations
-- -----------------------------------------------------------------------------
-- Represents CTA L train stations seeded from the Overpass API.
-- Stations are the anchors of the game map — POIs are discovered near them.
-- Declared before point_of_interests because POIs reference stations via FK.
-- The points column is dropped here: scoring lives on point_of_interests only.
-- Having two sources of truth for points would cause silent scoring bugs.
-- -----------------------------------------------------------------------------
CREATE TABLE stations (
    id            BIGSERIAL     PRIMARY KEY,            -- internal DB key, ties to point_of_interests.station_id
    station_name  VARCHAR(500)  NOT NULL,               -- human-readable name, e.g. "Harold Washington Library"
    longitude     DECIMAL(9, 6) NOT NULL,               -- DECIMAL(9,6) preserves ~1cm precision vs REAL's ~1m drift
    latitude      DECIMAL(9, 6) NOT NULL                -- same precision fix — critical for geofence validation
);


-- -----------------------------------------------------------------------------
-- TABLE: point_of_interests
-- -----------------------------------------------------------------------------
-- All visitable locations in the game: CTA stations AND nearby POIs like museums,
-- parks, or landmarks. station_id is NULLABLE — a POI with station_id = NULL is
-- a standalone location not anchored to any specific train stop.
-- If a station is deleted, ON DELETE SET NULL preserves the POI rather than
-- cascade-deleting it, since the location itself still exists in the real world.
-- stamp_book_entries.location_id references this table — every stamp is a POI.
-- -----------------------------------------------------------------------------
CREATE TABLE point_of_interests (
    id            BIGSERIAL     PRIMARY KEY,            -- PK referenced by stamp_book_entries.location_id
    poi_name      VARCHAR(500)  NOT NULL,               -- display name shown on map markers and stamp book grid
    longitude     DECIMAL(9, 6) NOT NULL,               -- DECIMAL(9,6) for coordinate precision (fix #4)
    latitude      DECIMAL(9, 6) NOT NULL,               -- used by geofence check on POST /checkin
    station_id    BIGINT,                               -- NULLABLE (fix #6): NULL = standalone POI, not station-tied
    points        INTEGER       NOT NULL DEFAULT 0,     -- points awarded on check-in; authoritative score source (fix #5)
    CONSTRAINT fk_station FOREIGN KEY (station_id)
        REFERENCES stations(id) ON DELETE SET NULL      -- station deleted → POI survives with station_id = NULL
);


-- -----------------------------------------------------------------------------
-- TABLE: stamp_books
-- -----------------------------------------------------------------------------
-- One stamp book per user — enforced by UNIQUE on user_id.
-- Acts as the container/inventory bag between users and their stamp entries.
-- Created automatically when a user registers via StampBookService.
-- ON DELETE CASCADE means deleting a user also deletes their stamp book,
-- which in turn cascades to all stamp_book_entries (see that table's FK).
-- -----------------------------------------------------------------------------
CREATE TABLE stamp_books (
    id      BIGSERIAL PRIMARY KEY,
    user_id BIGINT    NOT NULL UNIQUE,                  -- UNIQUE: one book per user, no exceptions
    CONSTRAINT fk_stamp_books_user FOREIGN KEY (user_id)
        REFERENCES profiles(id) ON DELETE CASCADE          -- user deleted → stamp book deleted → entries deleted
);


-- -----------------------------------------------------------------------------
-- TABLE: stamp_book_entries
-- -----------------------------------------------------------------------------
-- One row per (stamp_book, point_of_interest) pair.
-- All entries are pre-populated at registration with visited = FALSE.
-- When a user checks in via POST /checkin, the matching row flips to visited = TRUE
-- and visited_at is set. This design means the stamp book grid always has a full
-- set of slots — like a Pokédex where every entry exists, most are just "unseen."
-- The UNIQUE constraint on (stamp_book_id, location_id) prevents duplicate stamps
-- for the same location — the DB enforces this, not just application code.
-- weekly score resets (every Monday) do NOT touch this table — stamps are permanent.
-- -----------------------------------------------------------------------------
CREATE TABLE stamp_book_entries (
    id            BIGSERIAL PRIMARY KEY,                -- entry PK
    stamp_book_id BIGINT    NOT NULL,                   -- which stamp book this slot belongs to
    location_id   BIGINT    NOT NULL,                   -- which POI this slot represents (fix #3: matches table name)
    visited       BOOLEAN   NOT NULL DEFAULT FALSE,     -- flips to TRUE on successful check-in
    visited_at    TIMESTAMP,                            -- NULL until stamped; set on POST /checkin
    CONSTRAINT fk_entries_stamp_book FOREIGN KEY (stamp_book_id)
        REFERENCES stamp_books(id) ON DELETE CASCADE,   -- book deleted → all its entries deleted
    CONSTRAINT fk_entries_location FOREIGN KEY (location_id)
        REFERENCES point_of_interests(id) ON DELETE CASCADE, -- POI deleted → remove its stamp slots
    CONSTRAINT uq_entry UNIQUE (stamp_book_id, location_id)  -- no duplicate slots per book per location
);


-- =============================================================================
-- QUICK REFERENCE — HOW TABLES TALK TO EACH OTHER
-- =============================================================================
--
--  INSERT a user:
--      → INSERT INTO users ...
--      → INSERT INTO stamp_books (user_id) VALUES (new_user_id)
--      → INSERT INTO stamp_book_entries for every row in point_of_interests
--         with visited = FALSE (handled by StampBookService on registration)
--
--  CHECK IN (POST /checkin):
--      → Verify user is within radius of point_of_interests.latitude/longitude
--      → UPDATE stamp_book_entries SET visited = TRUE, visited_at = NOW()
--         WHERE stamp_book_id = (SELECT id FROM stamp_books WHERE user_id = ?)
--           AND location_id = ?
--      → UPDATE users SET weekly_score = weekly_score + points,
--                         hi_score = GREATEST(hi_score, weekly_score + points)
--         WHERE id = ?  (points pulled from point_of_interests.points)
--
--  WEEKLY RESET (every Monday midnight):
--      → UPDATE users SET weekly_score = 0
--      → stamp_book_entries is NOT touched — stamps are permanent
--
--  DELETE a user:
--      → CASCADE removes: stamp_books → stamp_book_entries (automatic)
--      → point_of_interests and stations are unaffected
--
-- =============================================================================