-- =============================================================================
-- THE LOOP SCAVENGER HUNT — SQLite Schema
-- This document was generated by Claude and reviewed/edited
-- =============================================================================
-- SQLite does not require a running server.
-- This schema is applied once to create loop_scavenger_hunt.db.
-- The .db file is then committed to Git and shared across the team.
-- =============================================================================

-- Enforce foreign key support — SQLite disables FK checks by default
PRAGMA foreign_keys = ON;


-- -----------------------------------------------------------------------------
-- TABLE: profiles
-- Root entity. Deleting a profile cascades to stamp_books → stamp_book_entries.
-- Renamed from 'users' to 'profiles' per team decision.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profiles (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    username      TEXT    NOT NULL UNIQUE,
    email         TEXT    NOT NULL UNIQUE,
    password_hash TEXT    NOT NULL,
    hi_score      INTEGER NOT NULL DEFAULT 0,
    weekly_score  INTEGER NOT NULL DEFAULT 0,
    created_at    TEXT    NOT NULL DEFAULT (datetime('now'))  -- ISO 8601 UTC
);


-- -----------------------------------------------------------------------------
-- TABLE: point_of_interests
-- All visitable locations — both CTA stations and nearby POIs live here.
--
-- SELF-REFERENCING DESIGN:
--   station_id is a self-reference back to this same table.
--   A row is a STATION  if: station_id IS NOT NULL AND station_id = id
--   A row is a POI      if: station_id IS NOT NULL AND station_id != id
--   A row is STANDALONE if: station_id IS NULL
--
-- INSERT ORDER for stations:
--   Stations must be inserted in two steps because the self-referencing id
--   is not known until after the row exists:
--     Step 1: INSERT with station_id = NULL
--     Step 2: UPDATE SET station_id = id WHERE id = <new_id>
--   See seed_mock_data.py for the exact pattern.
--
-- FK NOTE (fix applied):
--   The original schema declared station_id with no FOREIGN KEY constraint,
--   meaning any integer (including non-existent ids) could be stored silently.
--   A self-referencing FK is added here so SQLite enforces referential integrity.
--   ON DELETE SET NULL: if a station row is deleted, linked POIs become standalone.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS point_of_interests (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    poi_name    TEXT    NOT NULL,
    longitude   REAL    NOT NULL,
    latitude    REAL    NOT NULL,
    station_id  INTEGER,              -- NULL = standalone | = id → station | != id → POI linked to station
    points      INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_poi_station FOREIGN KEY (station_id)   -- fix: self-referencing FK was missing
        REFERENCES point_of_interests(id) ON DELETE SET NULL
);


-- -----------------------------------------------------------------------------
-- TABLE: stamp_books
-- One per profile. Deletion cascades from profiles via ON DELETE CASCADE.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stamp_books (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    profile_id INTEGER NOT NULL UNIQUE,  -- UNIQUE: one book per profile
    CONSTRAINT fk_stamp_books_profile FOREIGN KEY (profile_id)
        REFERENCES profiles(id) ON DELETE CASCADE
);


-- -----------------------------------------------------------------------------
-- TABLE: stamp_book_entries
-- One row per (stamp_book, POI) pair. Pre-populated as visited = 0 on registration.
-- visited flips to 1 on successful check-in. Stamps survive weekly score resets.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stamp_book_entries (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    stamp_book_id INTEGER NOT NULL,
    location_id   INTEGER NOT NULL,
    visited       INTEGER NOT NULL DEFAULT 0,   -- 0 = false, 1 = true
    visited_at    TEXT,                          -- NULL until stamped; ISO 8601 string
    CONSTRAINT fk_entries_stamp_book FOREIGN KEY (stamp_book_id)
        REFERENCES stamp_books(id) ON DELETE CASCADE,
    CONSTRAINT fk_entries_location FOREIGN KEY (location_id)
        REFERENCES point_of_interests(id) ON DELETE CASCADE,
    CONSTRAINT uq_entry UNIQUE (stamp_book_id, location_id)
);